### ISSUE TITLE
Error: 404 not found

### ISSUE THREAD

**Issue by soyo-kaze** [Diversity-In-DSC/DSC-WOW#34]
Add 404 not found page redirection. 
(Suggested package: React-Router)

**Comment by ishandeveloper** [comment]
@soyo-kaze Thanks for taking the time to create this issue , I'll be self-assigning this one, and let you know once it's fixed.

**Comment by soyo-kaze** [comment]
oh okay I thought I could do that but that's okay 😄 👍

**Comment by ishandeveloper** [comment]
@soyo-kaze Since, we just launched the website, I wanted to fix all the known issues in a bit hurry 😅 

Feel free to create another one in case you find any more bugs or anything, and I'll assign it to you : )

**Comment by soyo-kaze** [comment]
👍 👍
